# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_hal_wdt/test_apps/wdt_rom_impl:
  disable:
    - if: SOC_WDT_SUPPORTED != 1
  depends_components:
    - esp_hal_wdt
