# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_driver_pcnt/test_apps/pulse_cnt:
  disable:
    - if: SOC_PCNT_SUPPORTED != 1
  disable_test:
    - if: IDF_TARGET == "esp32c5"
      temporary: true
      reason: target test failed  # TODO [ESP32C5] IDF-10342
  depends_components:
    - esp_driver_pcnt
