# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_driver_gpio/test_apps:
  depends_components:
    - esp_driver_gpio
  disable:
    - if: IDF_TARGET in ["esp32h21"]
      temporary: true
      reason: not support yet # TODO: [esp32h21] IDF-11611

components/esp_driver_gpio/test_apps/gpio_extensions:
  enable:
    - if: SOC_DEDICATED_GPIO_SUPPORTED == 1
    - if: SOC_GPIO_SUPPORT_PIN_GLITCH_FILTER == 1 or SOC_GPIO_FLEX_GLITCH_FILTER_NUM > 0
  depends_components:
    - esp_driver_gpio
