# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_driver_gpio/test_apps:
  disable_test:
    - if: IDF_TARGET in ["esp32p4", "esp32c5"]
      temporary: true
      reason: test not pass, should be re-enable # TODO: [ESP32P4] IDF-8968 [ESP32C5] IDF-10331
  depends_components:
    - esp_driver_gpio

components/esp_driver_gpio/test_apps/gpio_extensions:
  enable:
    - if: SOC_DEDICATED_GPIO_SUPPORTED == 1
    - if: SOC_GPIO_SUPPORT_PIN_GLITCH_FILTER == 1 or SOC_GPIO_FLEX_GLITCH_FILTER_NUM > 0
  depends_components:
    - esp_driver_gpio
