components/hal/test_apps/crypto:
  depends_components:
    - efuse
    - mbedtls
    - esp_security

components/hal/test_apps/hal_i2c:
  disable:
    - if: SOC_I2C_SUPPORTED != 1

components/hal/test_apps/hal_utils:
  enable:
    - if: IDF_TARGET == "linux"

components/hal/test_apps/tee_apm:
  disable:
    - if: IDF_TARGET not in ["esp32c6", "esp32h2", "esp32c5", "esp32c61"]
