# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_driver_uart/test_apps/rs485:
  disable:
    - if: SOC_UART_SUPPORTED != 1
    - if: IDF_TARGET in ["esp32h21"]
      temporary: true
      reason: not support yet # TODO: [esp32h21] IDF-11618
  disable_test:
    - if: IDF_TARGET != "esp32"
      temporary: true
      reason: lack of runners
  depends_components:
    - esp_driver_uart
    - esp_driver_gpio

components/esp_driver_uart/test_apps/uart:
  disable:
    - if: SOC_UART_SUPPORTED != 1
    - if: IDF_TARGET in ["esp32h21"]
      temporary: true
      reason: not support yet # TODO: [esp32h21] IDF-11618
  depends_components:
    - esp_driver_uart
    - esp_driver_gpio

components/esp_driver_uart/test_apps/uart_vfs:
  depends_components:
    - esp_driver_uart
    - vfs
