components/esp_driver_sdmmc/test_apps/sdmmc:
  disable:
    - if: SOC_SDMMC_HOST_SUPPORTED != 1

  depends_components:
    - sdmmc
    - esp_driver_sdmmc
    - esp_hal_sd
    - esp_hw_support
    - soc
