# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

examples/openthread/ot_br:
  disable:
    - if: IDF_TARGET in ["esp32h2"]
      temporary: true
      reason: target(s) not supported yet
  disable_test:
    - if: IDF_TARGET in ["esp32", "esp32c3", "esp32c2", "esp32c6", "esp32s2"]
      temporary: true
      reason: only test on esp32s3

examples/openthread/ot_cli:
  enable:
    - if: SOC_IEEE802154_SUPPORTED == 1

examples/openthread/ot_rcp:
  enable:
    - if: SOC_IEEE802154_SUPPORTED == 1
  disable_test:
    - if: IDF_TARGET not in ["esp32h2", "esp32c6"]
      temporary: true
      reason: only test on esp32h2 and esp32c6

examples/openthread/ot_sleepy_device/deep_sleep:
  enable:
    - if: SOC_IEEE802154_SUPPORTED == 1
  disable_test:
    - if: SOC_IEEE802154_SUPPORTED == 1
      temporary: true
      reason: Unsupport # TO-DO: TZ-134

examples/openthread/ot_sleepy_device/light_sleep:
  enable:
    - if: SOC_IEEE802154_SUPPORTED == 1

examples/openthread/ot_trel:
  enable:
    - if: SOC_WIFI_SUPPORTED == 1
  disable_test:
    - if: IDF_TARGET not in ["esp32c6", "esp32s3"]
      reason: only test on esp32c6 and esp32s3
