components/nvs_flash/host_test:
  enable:
    - if: IDF_TARGET == "linux"

components/nvs_flash/test_apps:
  disable_test:
    - if: IDF_TARGET not in ["esp32", "esp32c3"]
      temporary: true
      reason: NVS flash test on one Xtensa and one RISCV target is enough
