# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_driver_ppa/test_apps:
  disable:
    - if: SOC_PPA_SUPPORTED != 1
  depends_components:
    - esp_driver_ppa
    - esp_driver_dma
    - esp_hal_ppa
    - esp_hw_support
    - soc
