# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/driver/test_apps/legacy_adc_driver:
  disable:
    - if: SOC_ADC_SUPPORTED != 1
  disable_test:
    - if: IDF_TARGET == "esp32c61"
      temporary: true
      reason: lack of runners
  depends_components:
    - efuse
    - esp_driver_i2s
    - esp_driver_spi
  depends_filepatterns:
    - components/driver/deprecated/**/*adc*

components/driver/test_apps/legacy_i2c_driver:
  disable:
    - if: SOC_I2C_SUPPORTED != 1
  disable_test:
    - if: IDF_TARGET != "none"
      temporary: false
      reason: disable target test for legacy i2c driver.

components/driver/test_apps/legacy_mcpwm_driver:
  disable:
    - if: SOC_MCPWM_SUPPORTED != 1
  depends_filepatterns:
    - components/driver/deprecated/**/*mcpwm*

components/driver/test_apps/legacy_rmt_driver:
  disable:
    - if: SOC_RMT_SUPPORTED != 1
  depends_filepatterns:
    - components/driver/deprecated/**/*rmt*

components/driver/test_apps/legacy_sigma_delta_driver:
  disable:
    - if: SOC_SDM_SUPPORTED != 1
  depends_filepatterns:
    - components/driver/deprecated/**/*sigma*
  depends_components:
    - esp_driver_gpio

components/driver/test_apps/legacy_twai:
  disable:
    - if: SOC_TWAI_SUPPORTED != 1 or SOC_TWAI_SUPPORT_FD == 1
      reason: legacy driver doesn't support FD
  depends_filepatterns:
    - components/driver/twai/**/*
  depends_components:
    - esp_driver_gpio

components/driver/test_apps/touch_sensor_v1:
  disable:
    - if: SOC_TOUCH_SENSOR_VERSION != 1

components/driver/test_apps/touch_sensor_v2:
  disable:
    - if: SOC_TOUCH_SENSOR_VERSION != 2
