# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_driver_mcpwm/test_apps/mcpwm:
  disable:
    - if: SOC_MCPWM_SUPPORTED != 1
  disable_test:
    - if: IDF_TARGET == "esp32c5"
      temporary: true
      reason: test not pass, should be re-enable # TODO: [ESP32C5] IDF-10334
  depends_components:
    - esp_driver_mcpwm
